### ISSUE TITLE
Consider using nginx instead of Apache?

### ISSUE THREAD

**Issue by mattneal-stafflink** [codeispoetry/wp-codespace#4]
See title. I'm new to Codespaces, so I'm looking into doing this myself, but I think most modern environments prefer nginx over apache these days.

**Comment by codeispoetry** [comment]
Thank you for your comment. You are right. I used apache, because I know apache and how to configure it. Feel free to use any other server software.
I think, for the scope of Wordpress development, it doesn't matter, which server you app is running on.
